### ISSUE TITLE
On my school WiFi only connections to https work

### ISSUE THREAD

**Issue by meter1060** [mozilla/node-janus#57]
As the title says only connections to https work on my school's WiFi. Whereas insecure connections using the proxy and the add-on work on my mobile data.

**Comment by eamsen** [comment]
That's interesting. Some more client-side info could help us. The easiest way to get that, would be to use the `Report Bug` feature using the latest [add-on version](https://github.com/mozilla/janus-addon/blob/master/janus.xpi).

Does your school use a VPN?

**Comment by matttbe** [comment]
Hello,
I also have this problem simply because the port use by your proxy is blocked.
Is it maybe possible to use another port (80) and/or automatically disable the use of the proxy if we can't be connected to this port?

PS: thank you for developing this great tool :-)

**Comment by eamsen** [comment]
You can configure the ports as you like, when running your own proxy instance, but we don't have plans to tunnel the traffic through other ports on our proxy instance, as port 80 will be used otherwise in future.

Currently, the add-on fetches the PAC on port 80 and the proxy tunnels traffic through port 44300. I expect the latter port to be blocked for you, so you end up with an active proxy (because 80 is open) but blocked requests.

Soon (#67), we will serve the PAC through 44300, too, so then you will fail to fetch the PAC if the port is blocked and would therefore never activate the proxy settings.

**Comment by eamsen** [comment]
Closing for now, unless @meter1060 reports back on this not being a blocked port issue.
